# Generated by Django 6.0 on 2025-12-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='login_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
