# Generated by Django 6.0 on 2025-12-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo_winner',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/winners/', verbose_name='Foto Ganador'),
        ),
    ]
