# Generated by Django 6.0 on 2025-12-07 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_candidate_photo_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingperiod',
            name='manual_winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_periods', to='voting.candidate', verbose_name='Ganador Manual'),
        ),
    ]
