# Generated by Django 6.0 on 2025-12-08 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_votingperiod_manual_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='nomination_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Nominación'),
        ),
    ]
