# Generated by Django 6.0 on 2025-12-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_candidate_nomination_reason'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votingperiod',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='votingperiod',
            name='voting_type',
            field=models.CharField(choices=[('MVP_MONTH', 'MVP del Mes'), ('BALON_ORO', 'Balón de Oro del Curso'), ('PUSKAS', 'Puskas')], default='MVP_MONTH', max_length=20, verbose_name='Tipo de Votación'),
        ),
        migrations.AlterUniqueTogether(
            name='votingperiod',
            unique_together={('month', 'year', 'voting_type')},
        ),
    ]
