# Generated by Django 6.0 on 2025-12-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_alter_votingperiod_voting_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingperiod',
            name='voting_type',
            field=models.CharField(choices=[('MVP_MONTH', 'MVP del Mes'), ('THE_BEST_CUATRI_1', 'The Best of the Cuatri 1 (Sep-Dic)'), ('THE_BEST_CUATRI_2', 'The Best of the Cuatri 2 (Ene-May)'), ('BALON_ORO', 'Balón de Oro del Curso'), ('PUSKAS', 'Puskas'), ('BOTA_ORO_ANO', 'Bota de Oro del Año')], default='MVP_MONTH', max_length=20, verbose_name='Tipo de Votación'),
        ),
    ]
