# Generated by Django 6.0 on 2025-12-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_alter_votingperiod_voting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='video_speech',
            field=models.FileField(blank=True, null=True, upload_to='candidates/videos/', verbose_name='Video Discurso'),
        ),
    ]
