# Generated by Django 6.0 on 2025-12-30 14:15

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_candidate_video_speech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='video_speech',
            field=models.FileField(blank=True, help_text='Sube un video de discurso (formato mp4, mov, avi)', null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='candidates/videos/', verbose_name='Video Discurso'),
        ),
    ]
